apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: punkrelique/poster-backend
          name: backend
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DbConnectionString
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.stage }}
          ports:
            - containerPort: 80

