name: docker ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 6'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the frontend Docker image
      run: docker build -f src/client/Dockerfile -t punkrelique/poster-frontend:latest -C src/client .

    - name: Push the frontend Docker image
      run: docker push punkrelique/poster-frontend:latest
      
    - name: Build the backend Docker image
      run: docker build -f src/server/Poster.Api/Dockerfile -t punkrelique/poster-frontend:latest -C src/server .
      
    - name: Push the frontend Docker image
      run: docker push punkrelique/poster-backend:latest
